name: sample

on: workflow_dispatch

jobs:
  create-cluster-deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: create the kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          config: config.yaml
      - name: deploy to the cluster and test
        run: |
          echo 'start'
          kubectl get pods
          echo 'before applying ingress'
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          echo 'after applying ingress'
          kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=90s
          echo 'after ingress comes online'
          kubectl get pods
          echo 'before applying usage'
          kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/usage.yaml
          echo 'after applying usage'
          kubectl get pods
          # should output "foo"
          echo 'before testing usage'
          curl localhost/foo
          # should output "bar"
          curl localhost/bar
          echo 'before testing usage'
